# Site settings
title: "Practo Engineering Blog"
logo: logo.svg
email: devops@practo.com
description: >
    Engineering blog fro Practo
url: "http://practo.github.io"
twitter_username: practo
github_username:  practo

# Build settings
markdown: kramdown
